finish article about scope functions in kotlin
osscameroon/blog pull request #13
Opened 2022-11-13 20:31 UTC by othimar

This is a beginner level article about scope functions in kotlin.

2022-11-14 15:00 UTC, RMPR requested changes
Thanks for the PR, I left some comments on the article.

2022-11-14 15:00 UTC, RMPR commented on data/blog/improve-your-kotlin-code-with-scope-functions.mdx
> +The **context** is an object on wich you call a function. The word **it** refers to the context. Anything declared inside the lambda is not accessible outside. The function `let` returns the result o
```suggestion
The **context** is an object on which you call a function. The word **it** refers to the context. Anything declared inside the lambda is not accessible outside. The function `let` returns the result of the lambda.
```

2022-11-14 15:00 UTC, RMPR commented on data/blog/improve-your-kotlin-code-with-scope-functions.mdx
> +It's a common practice to use `let` with the safe-call operator `?.` to performs an action if an object is not `null`.
Maybe add a link to the official documentation regarding the safe-call operator?

2022-11-14 15:00 UTC, RMPR commented on data/blog/improve-your-kotlin-code-with-scope-functions.mdx
> +    }
Why do you indent inside a code block?

2022-11-14 15:00 UTC, RMPR commented on data/blog/improve-your-kotlin-code-with-scope-functions.mdx
> +    }
Same question about indentation.

2022-11-14 15:00 UTC, RMPR commented on data/blog/improve-your-kotlin-code-with-scope-functions.mdx
> +    }
Indentation

2022-11-14 15:00 UTC, RMPR commented on data/blog/improve-your-kotlin-code-with-scope-functions.mdx
> +    window.show
Indentation

2022-11-14 15:00 UTC, RMPR commented on data/blog/improve-your-kotlin-code-with-scope-functions.mdx
> +    }
Indentation

2022-11-14 15:00 UTC, RMPR commented on data/blog/improve-your-kotlin-code-with-scope-functions.mdx
> +    dog.also{ it.bark()}.also{ it.sleep()}.also{ it.cry()}
Indentation.

2022-11-24 08:29 UTC, RMPR requested changes
The indentation still looks odd to me, can you run your codes through a tool like [ktlint](https://github.com/facebook/ktfmt) or Intellij then simply paste them in the code blocks?

2022-11-25 13:50 UTC, RMPR requested changes
It looks much better. Can you also remove the files `package-lock.json` and `yarn.lock`? Once you are done with that, [squash your commits](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits) and I'll merge.

2022-11-25 14:16 UTC, RMPR requested changes
Sorry if I was a bit unclear, I didn't mean to ~remove yarn.lock but not to commit your changes to it, so instead of deleting it, restoring it with something like git reset.

2022-11-25 19:19 UTC, closed without merging

2022-11-25 19:19 UTC, othimar commented
restarting it from zero.